"""Original teaching compositions; service claims follow the existing course content."""
D={}
def add(id,title,subtitle,kind,foot,**kw):D[id]=dict(title=title,subtitle=subtitle,kind=kind,foot=foot,**kw)
def flow(id,title,subtitle,steps,evidence,control,foot,**kw):add(id,title,subtitle,'workflow',foot,steps=steps,evidence=evidence,control=control,**kw)
def compare(id,title,subtitle,items,foot):add(id,title,subtitle,'compare',foot,items=items)
def lanes(id,title,subtitle,rows,foot,**kw):add(id,title,subtitle,'lanes',foot,rows=rows,**kw)
def orbit(id,title,subtitle,center,centerSub,items,foot,**kw):add(id,title,subtitle,'orbit',foot,center=center,centerSub=centerSub,items=items,**kw)

add('m1-s2','Rules, learning, and prediction','An algorithm learns a model; inference applies that model to a new example.','rules','A new prediction request does not, by itself, retrain the model.')
lanes('m1-s3','AI in a bicycle workshop','Start with a work task, then connect the prediction or generated output to an operational result.',[
 ('chart','Repair history','Forecast parts demand','Reorder before a stockout'),('eye','Inspection photograph','Detect damaged components','Send flagged parts for review'),('speech','Customer call','Transcribe and analyze','Search the issue by topic'),('doc','Technician notes','Summarize the repair','Prepare the next handoff')], 'Measure the outcome against the current process; review errors with substantial consequences.')
add('m1-s5','Recognizing data formats','Different source structures need different preparation and representation methods.','formats','For time series, preserve time ordering when separating training and evaluation data.')
add('m1-s6','Three ways a model can learn','The learning signal determines the task: a known target, hidden structure, or a reward.','learning','Choose the learning approach by the available evidence and the decision you need to make.')
add('m1-s7','Learning representations in a neural network','Layers transform inputs; training adjusts the strength of their connections.','network','More layers do not guarantee a better model. Compare data needs, compute, quality, and explainability.')
compare('m1-s10','Images and documents: choose by the output','An inspection photo and a scanned invoice need different kinds of analysis.',[
 ('Amazon Rekognition','photo','Image or video → objects and other supported image-analysis results.','Example: identify a component in an inspection photograph.'),
 ('Amazon Textract','table','Scanned document → extracted text, tables, and form fields.','Then analyze extracted text with Comprehend when needed.')], 'Extraction, visual recognition, and language analysis are distinct tasks.')
add('m1-s11','Speech, language, and user experiences','Select the service by the transformation or user capability required.','language','Lex supports conversational interfaces; Personalize uses interaction data for recommendations.')
add('m1-s12','The machine learning lifecycle','Approved lifecycle composition.','approved-lifecycle','')
flow('m1-s13','Data preparation with AWS Glue','Make source data usable, discoverable, and traceable before it reaches a model.',[
 ('db','Inspect sources','Missing values, duplicates, permissions'),('gear','Prepare with Glue','Integrate and transform records'),('book','Catalog metadata','Record structure and meaning'),('chip','Consume the data','Use a versioned dataset')],
 ('TRACE ONE TRANSFORMATION','PREPARATION RECORD','source version → recipe → output version'),
 'A catalog describes data; it is not a replacement for the dataset. DataBrew recipes support repeatable preparation.',
 'Inspect quality and permitted use before training; preserve the transformation history.')
add('m1-s15','Training, tuning, and independent testing','Use separate data for learning, choosing a candidate, and assessing the final choice.','training','Learned weights are model parameters. Learning rate is an example of a hyperparameter.')
add('m1-s16','Choosing an inference pattern','Match response timing and workload shape to the serving approach.','inference','Serverless is a capacity option; compare supported features, startup behavior, and workload needs.')
add('m1-s18','Reading a confusion matrix','Inspection example: 80 components, of which 24 actually have a defect.','matrix','“Positive” means the model raises a defect alert; each component occupies exactly one cell.')
add('m1-s19','Precision, recall, accuracy, and F1','The same 80 inspections answer different quality questions.','metrics','Choose metrics by the cost of missed defects and unnecessary inspections, not by the largest score.')
orbit('m2-s1','The foundation model lifecycle','Match the modality and adaptation effort to the task, then evaluate in operation.','Useful generated content','Text • image • audio • other modalities',[
 ('search','Select','Choose task, data, modality, and model.'),('gear','Adapt','Prompt, retrieve, or train when justified.'),('check','Evaluate','Measure task quality and safety.'),('chart','Operate','Monitor outcomes and feed back errors.')], 'Understanding an image and generating an image are different model capabilities.')
add('m2-s3','Tokens, chunks, and embeddings','Tokenization controls model input; chunking and embeddings support retrieval.','embeddings','Chunk size is a trade-off: preserve useful context without adding unrelated material.')
add('m2-s4','How diffusion forms an image','Training learns denoising; generation repeatedly applies it, conditioned on a request.','diffusion','Schematic illustration. Latent diffusion operates in a compressed representation.')
add('m2-s5','An effective prompt has a clear job','Separate the instruction, source material, and required output.','prompt','Check the answer against the note: an instruction against invention is not a guarantee.')
compare('m2-s8','Measuring the value of a GenAI assistant','Compare the current workflow and the assisted workflow on the same task.',[
 ('Technical evidence','checklist','Evaluate correctness, response time, and representative difficult cases.','Retain failed requests and human review in the evaluation.'),
 ('Business evidence','series','Measure time to find an approved procedure and the effort to finish the job.','Include inference cost, review effort, and the cost of mistakes.')], 'Faster answers only create value when the complete task meets its quality requirements.')
add('m2-s9','Three ways to use AI on AWS','Bedrock, pretrained AI services, and SageMaker AI as three layers.','platform_layers','Identity, storage, compute, and monitoring connect to all three layers; you control data and permissions in each.')
add('m2-s10','Inference usage, capacity, and caching','Evaluate the whole request: repeated context, retrieved material, and generated output.','capacity','Pricing units, caching rules, capacity options, and model support vary; check the selected service.')
lanes('m2-s11','Tools across the agent solution','These tools serve different users and different parts of development and operation.',[
 ('person','Business work','Amazon Quick','Work across connected sources'),('code','Software development','Kiro','Coding assistant and command line'),('branch','Build agent logic','Strands Agents','Compose a model and tools'),('server','Run and operate','Bedrock AgentCore','Identity, memory, and monitoring')], 'An application, development tool, framework, and operating service can be used together.',left='NEED',middle='TOOL',right='ROLE')
add('m3-s2','How inference settings change generation','Sampling affects token selection; output limits affect where the response stops.','sampling','Illustrative distributions. Lower variation does not establish factual accuracy or identical responses.')
add('m3-s3','Retrieval-augmented generation','Approved RAG composition.','approved-rag','')
add('m3-s6','An agent chooses actions; tools execute them','Workshop example: check availability, propose an appointment, and authorize the booking.','agent','MCP or another tool connection does not grant permission; enforce access in the application and services.')
flow('m3-s9','Improving a prompt systematically','Change a prompt, measure the result, and keep evidence for the choice.',[
 ('doc','Specify the task','Instructions, marked source text, format'),('book','Add examples','Representative inputs and outputs'),('check','Evaluate candidates','The same cases and scoring rubric'),('flag','Select a version','Validate results against evidence')],
 ('KEEP THE COMPARISON REPRODUCIBLE','EVALUATION RECORD','prompt version • test cases • scoring rubric'),
 'Use difficult cases and missing-information cases. A generated explanation can be wrong even when it sounds coherent.',
 'Prompt engineering edits instructions; prompt tuning learns additional prompt parameters.',feedback='Revise and retest')
add('m3-s10','Prompt injection and defensive boundaries','A retrieved document can contain hostile instructions; treat it as data.','injection','No single prompt or filter closes every attack path. Test the complete application.')
add('m3-s13','Instruction tuning and human preferences','Curated examples teach task behavior; preference feedback guides a separate optimization objective.','tuning','Human preferences can contain bias and do not independently establish factual truth.')
compare('m3-s16','Evaluate generated content with multiple lenses','Each method measures part of quality; use a shared set of representative outputs.',[
 ('Reference metrics','doc','ROUGE and BLEU count matching words; BERTScore compares meaning.','Useful signals, with limits for meaning and correctness.'),
 ('Human review','person','Use a common rubric for accuracy, usefulness, safety, and instructions.','Review agreement and include difficult cases.'),
 ('Model as judge','scale','A separate model scores answers against a defined rubric.','Calibrate with human judgments; investigate bias.')], 'A judge score or similarity score is evidence, not ground truth.')
add('m3-s17','Measure the complete user workflow','Model quality must translate into a completed task with acceptable cost and effort.','business','Use the same workload and preset acceptance criteria; continue measuring after release.')
orbit('m4-s1','Responsible AI is a shared practice','Assess the behavior of the system and the consequences for the people using it.','Repair-priority model','A real decision affects a real user',[
 ('person','People','Fairness and meaningful human control.'),('check','Behavior','Safety and robustness under failure.'),('lock','Information','Privacy, transparency, permitted use.'),('book','Accountability','Explainability, governance, owners.')], 'Product, data, and operations teams each contribute evidence; one metric cannot cover all responsibilities.')
add('m4-s3','Why aggregate accuracy can mislead','A rare class can be missed even when the overall accuracy looks strong.','imbalance','Illustrative class-imbalance example; evaluate realistic held-out data and relevant subgroups.')
flow('m4-s4','Where unfair bias can enter','Trace the decision across the complete data and operating lifecycle.',[
 ('db','Collection','Missing locations or populations'),('person','Labeling','Inconsistent reviewer judgments'),('filter','Features','Inputs that stand in for a protected trait'),('chart','Deployment','New users and feedback loops')],
 ('INVESTIGATE THE MECHANISM','REVIEW QUESTION','Which groups or conditions are missing?'),
 'Compare inputs, model errors, and downstream decisions. Historical outcomes can preserve unequal treatment.',
 'Bias may originate before training or emerge after release; audit both data and outcomes.')
orbit('m4-s5','Reduce bias with measured evidence','A mitigation is a hypothesis to test, document, and monitor.','Compare before / after','Use metrics suited to the decision',[
 ('search','Inspect','Review sampling, labels, and proxies.'),('scale','Measure','Compare errors for relevant groups.'),('gear','Mitigate','Apply a justified data or model change.'),('chart','Monitor','Audit decisions after release.')], 'Retain the original result, revised result, mitigation rationale, and remaining limitations.',centerIcon='scale')
lanes('m4-s6','What makes a dataset responsible?','Evaluate both whether the data works and whether the intended use is permitted.',[
 ('eye','Coverage','Covers the real task and users','Record missing conditions'),('check','Quality','Labels, values, duplicates','Keep the validation results'),('key','Rights and privacy','Origin and permitted use','Restrict fields and access'),('calendar','Maintenance','Versions, refresh, retention','Keep evaluation separate')], 'More records do not automatically repair poor representation, poor labels, or missing rights.',left='DIMENSION',middle='CHECK',right='EVIDENCE / ACTION')
compare('m4-s7','Choose a model for its actual use','A benchmark score is one part of a release decision.',[
 ('Capability','network','Test the real task, hard cases, and known limitations.','Can a smaller model meet the requirement?'),('Efficiency','series','Compare compute use, latency, and total operating cost.','Include review and unsuccessful requests.'),('Responsibility','check','Assess safety behavior, transparency, and available controls.','Match controls to the impact of an error.')], 'Select using tested behavior under the intended conditions, rather than model size alone.')
add('m4-s8','Clarify: investigate bias before training','Inspect how examples and labels differ across relevant groups.','prebias','Illustrative counts. A numerical difference calls for investigation; it is not a fairness verdict.')
add('m4-s9','Clarify: investigate bias after training','Compare model outcomes and errors below the overall average.','postbias','Illustrative results. Repeat after retraining or population changes; retain the evaluation report.')
lanes('m4-s10','Risks in generated content','Connect each failure mode to evidence, controls, and escalation.',[
 ('doc','Unsupported claim','Approved sources and grounding','Verify the actual statement'),('check','Harmful advice','Policies, testing, and review','Escalate high-impact cases'),('book','Protected material','Rights and permitted-use review','Consult the appropriate owner'),('lock','Sensitive information','Access limits and content checks','Prevent inappropriate disclosure')], 'Fluent wording does not make a response reliable; choose controls for the consequences of failure.',left='FAILURE',middle='CONTROL',right='REVIEW')
add('m4-s11','Guardrails around model inputs and outputs','Configure supported checks, then test them with realistic failure cases.','guardrails','Guardrails complement permissions, retrieval controls, validation, and human review.')
add('m4-s12','Compare models on the same evidence','Retain the cases, rubric, model and prompt versions, and release threshold.','evaluation','Bedrock evaluation and appropriate SageMaker Clarify workflows support evaluation and analysis.')
lanes('m4-s15','Openness, license, and safety are separate','Inspect what is available, what is permitted, and what has actually been tested.',[
 ('chip','Model weights','Available to deploy or adapt?','Verify the specific release'),('code','Training details','Code or data disclosed?','Record what remains unknown'),('book','License terms','Use, modification, redistribution','Review applicable conditions'),('check','Safety evidence','Tests and operating controls','Evaluate the intended use')], 'Open weights do not imply open training data, unrestricted use, or established safety.',left='PROPERTY',middle='QUESTION',right='EVIDENCE')
add('m4-s17','Explaining a model prediction','Feature contributions help explain an alert; they do not establish causation.','contributions','Illustrative contributions, not a fitted model. Combine explanations with performance and domain knowledge.')
orbit('m4-s18','Design a meaningful human control loop','Give reviewers the information and authority needed to change an outcome.','A decision can be challenged','Preserve evidence and a correction path',[
 ('speech','Explain','Tell users the purpose and limits.'),('doc','Support','Show evidence and relevant context.'),('person','Review','Route uncertain or high-impact cases.'),('gear','Improve','Record corrections; investigate patterns.')], 'Feedback should enter a controlled improvement and release process, not an unreviewed training update.',centerIcon='person')
add('m4-s19','Human review with Amazon A2I','Route selected predictions to a reviewer who can inspect the original evidence.','review','Protect review data and check quality before using corrected examples in future training.')
add('m5-s4','S3 access: test allowed and denied paths','A private dataset still needs correctly scoped permissions for internal workloads.','s3access','Evaluate resource policies, identity permissions, and other applicable controls together.')
flow('m5-s5','Build a scoped SageMaker role','Start with the ML activity, then review access to the actual resources.',[
 ('gear','Select activities','Preparation, training, or operation'),('key','Role Manager','Generate starting permissions'),('search','Review the role','Actions, resources, conditions'),('server','Use role credentials','Run the intended workload')],
 ('SEPARATE DUTIES','ROLE SCOPE','training job reads only its approved data folder'),
 'Test both expected access and denied access. Keep preparation, development, and production responsibilities distinct.',
 'Generated permissions are a starting point; scope them to the job and the data.')
add('m5-s6','Encryption at rest and authorized access','Encrypt datasets, model artifacts, logs, backups, and relevant derived copies.','encryption','An identity permitted to decrypt and read can still disclose the content; encryption is one layer.')
add('m5-s7','KMS: data access and key access','An encrypted-data path depends on both storage permissions and permission to use the key.','kms','Coordinate key policy and lifecycle changes with dependent applications; investigate unexpected key use.')
flow('m5-s9','Find and handle sensitive data with Macie','Discover sensitive data in supported S3 objects, then decide how to respond.',[
 ('db','S3 objects','Buckets that Macie scans'),('search','Macie discovery','Find personal or sensitive data'),('flag','Investigate finding','Location, exposure, intended use'),('lock','Respond','Restrict, remove, or transform')],
 ('EXAMPLE DATA TREATMENT','MINIMIZED RECORD','name removed, job category kept'),
 'Choose masking, tokenization, or another suitable privacy technique. Removing obvious identifiers may leave reidentification risk.',
 'Discovery creates evidence; it does not automatically resolve every data-handling problem.')
add('m5-s10','CloudTrail and application audit evidence','Track who acted on which resource, while separately recording application behavior.','audit','Configure relevant supported events and retention; CloudTrail is not a full model conversation transcript.')
add('m5-s11','Three controls on one data path','A private subnet, gateway endpoint, IAM role, and KMS key around a SageMaker workload.','vpc_boundaries','Reachability, authorization, and encryption answer different questions. Test all three for every data path.')
add('m5-s12','Private access to SageMaker services','An interface endpoint connects a customer VPC to the managed service environment.','privatelink','Configure S3 and logging paths separately; PrivateLink connectivity does not replace IAM authorization.')
lanes('m5-s13','AI attack paths and layered controls','Protect the data, the application, and the operating environment.',[
 ('db','Poisoned data or sources','Known origin, restricted writes','Version approved inputs'),('doc','Prompt injection','Treat outside text as data','Constrain tool actions'),('eye','Extraction or disclosure','Access limits and output checks','Watch for repeated probing'),('chart','Abuse and incidents','Rate limits and investigation','Rehearse the response')], 'Test representative attacks across layers; infrastructure scanning alone does not evaluate AI behavior.',left='ATTACK PATH',middle='CONTROL',right='OPERATING EVIDENCE')
add('m5-s16','Record the complete release, not just a model','A reproducible result depends on data, transformations, learned artifacts, and application settings.','versions','Keep tested rollback paths and approvals alongside the versioned components.')
add('m5-s19','Trace model lineage to its inputs','Relationships help identify which artifacts and releases depend on a flawed source.','lineage','Training lineage explains model provenance; answer citations identify evidence used for a response.')
compare('m5-s21','Provider evidence and customer evidence','Use AWS reports as part of due diligence, alongside evidence from your own application.',[
 ('AWS Artifact','book','Access provider compliance reports and agreements.','Review their scope and the controls they describe.'),('Customer assessment','checklist','Assess data use, application settings, and operating controls.','Retain your configurations, tests, and review decisions.')], 'Provider reports alone do not establish that an application satisfies every requirement.')
add('m5-s23','Prioritize risk by likelihood and impact','Assess failure scenarios, assign owners, and revisit risk after mitigation.','risk','Illustrative prioritization matrix. Document assumptions, uncertainty, controls, and residual risk.')
add('m5-s24','Trace data location and retention','Include prompts, outputs, processing, logs, backups, and tools in the data-flow review.','residency','Verify the selected service, Region, configuration, and deletion or archival outcome against requirements.')
flow('m5-s25','Organize assessment evidence with Audit Manager','Collect and organize evidence, then assess the controls it is meant to support.',[
 ('doc','Collect sources','Supported logs and configurations'),('book','Organize evidence','Selected assessment framework'),('person','Review controls','Evaluate evidence and find gaps'),('gear','Remediate','Assign owner and track closure')],
 ('KEEP THE ASSESSMENT TRACEABLE','EVIDENCE RECORD','control, evidence source, review, action taken'),
 'Automation assists collection. Reviewers still assess effectiveness and whether the evidence covers the requirement.',
 'Artifact provides AWS reports; Audit Manager helps organize evidence for your assessments.')
add('m5-s26','AWS Config: desired state and change history','Record supported resource configurations and evaluate rules over time.','config','A resource configuration result does not establish that generated answers are accurate or fair.')
compare('m5-s27','Infrastructure findings and recommendations','Choose the tool by the type of evidence you need.',[
 ('Amazon Inspector','server','Identify supported software vulnerabilities and unintended network exposure.','Investigate findings in the covered workloads.'),('AWS Trusted Advisor','checklist','Review available recommendations for security, reliability, performance, and cost.','Act on relevant account and configuration guidance.')], 'Use these alongside AI-specific tests for prompt injection, unsafe outputs, and tool authorization.')
orbit('m5-s28','Govern data throughout its lifecycle','Make each collection, access, quality, sharing, and disposal decision accountable.','A governed dataset','Catalog • classification • lineage',[
 ('person','Own','Name who approves purpose and use.'),('book','Understand','Document meaning, sources, and limits.'),('key','Protect','Control access and onward sharing.'),('calendar','Maintain','Monitor quality, retention, and disposal.')], 'Include derived datasets and evaluation copies in the same governance review.',centerIcon='db')
flow('m5-s29','Discover, prepare, and approve a dataset','A clean dataset still needs a documented purpose and permission to use it.',[
 ('book','Discover sources','Catalog, structure, ownership'),('gear','Prepare repeatably','Glue or DataBrew transformations'),('db','Version the output','Keep the recipe and source references'),('check','Approve use','Quality and permitted purpose')],
 ('TRACE THE CURATION','DATASET MANIFEST','source version, recipe, curated output version'),
 'Review permissions separately from technical cleanup. Keep source meaning and ownership with the transformed data.',
 'An approved dataset needs both technical quality evidence and a valid intended use.')
add('m5-s30','Retention ladder and governed lake access','S3 storage classes over time, then Lake Formation permissions.','retention_ladder','Test who can actually read the data and that expired objects are gone. A configured rule needs evidence.')
add('m5-s31','Security scope grows with what you build','Apply controls to the components you manage, from application use through model training.','scopes','Provider-managed components still require due diligence and a clear responsibility boundary.')
add('m5-s32','Assign controls to components and owners','Map the actual system before deciding who must supply each control and its evidence.','ownership','Confirm agreements for vendor-managed components and operating owners for customer-managed components.')
orbit('m5-s33','An operating process for AI governance','Govern changes to models, prompts, data, tools, and the people using them.','Accountable operation','Named owners • recorded decisions',[
 ('book','Define','Acceptable use, risk limits, criteria.'),('check','Release','Evaluate, approve, record versions.'),('chart','Operate','Monitor incidents and user feedback.'),('person','Learn','Train staff and review improvements.')], 'Teach people to protect data, challenge outputs, recognize limitations, and escalate problems.',centerIcon='book')
add('m5-s36','Validate claims before relying on an answer','A citation must support the specific statement beside it.','grounding','Measure abstentions and escalations too; a model’s self-rated confidence is not proof.')
add('m6-s1','The five AIF-C01 exam domains','The official domain weights guide review emphasis; teaching modules use a different sequence.','domains','The course keeps its teaching proportions; slide counts are not exam-question percentages.')
flow('m6-s3','Check readiness with fresh evidence','Use each objective to test understanding, application, and the ability to reject alternatives.',[
 ('book','Map objectives','Explain the concept in your words'),('branch','Try a new scenario','Choose and justify an approach'),('search','Diagnose errors','Explain why alternatives fail'),('gear','Target the gap','Revisit, then try a fresh case')],
 ('RECORD THE LEARNING GAP','REVIEW NOTE','objective, why you missed it, next exercise'),
 'Use official preparation for all question formats. An unfamiliar scenario gives better evidence than memorized wording.',
 'The 11 course checkpoints sample concepts; they are not a full practice exam or a pass predictor.',feedback='Fresh scenario')
lanes('m6-s4','Use official exam and preparation information','Check current information through the official AWS routes.',[
 ('book','Exam scope','AWS certification page','Read the current exam guide'),('code','Learning and practice','AWS Skill Builder','Review available preparation'),('calendar','Scheduling','Official registration flow','Check delivery and availability'),('person','Before the appointment','Candidate requirements','Review the applicable instructions')], 'Availability and access requirements can change; follow the current official information.',left='NEED',middle='OFFICIAL ROUTE',right='ACTION')
# v0.13 concept diagrams
add('m1-s4','The same shipment task, four kinds of software','Nested AI families beside four approaches to one task.','rules_to_agents','Deep learning is one family of ML; most foundation models are deep learning models.')
add('m1-s9','Four problem types: what the output is','Classification, regression, clustering, and anomaly detection as small plots.','problem_types','Binary classification has two labels; multiclass has more. Choose by the decision you need.')
add('m2-s2','One agent loops; several agents coordinate','An agent loop with memory and boundaries, plus two multi-agent patterns.','agentic','More agents add coordination cost and failure points. MCP connects tools; it does not grant permission.')
add('m3-s7','Examples in the prompt, not in the model','Three literal prompts showing zero-shot, one-shot, and few-shot.','shots','Examples guide the answer during inference only. Fine-tuning is what changes model weights.')
add('m3-s14','More customization, more cost to build and keep','A ladder from prompting to pretraining, with distillation below.','customization','Compare each option with an uncustomized baseline on the same evaluation set before committing.')
add('m4-s2','Bias and variance: how a model fits','Three fitted curves on the same data with training and new-data error.','fit','Statistical bias here is model simplicity. Unfair treatment of groups is a separate concern; test both.')
add('m5-s1','Shared responsibility for an AI application','Customer and AWS layers with examples of where the line falls.','shared','A managed model never decides which customer records your application may disclose. You do.')
assert len(D)==78,len(D)
